### PR TITLE
[WIP] - Rebranding

### PR DESCRIPTION
**Pull request by klinki**
Rebranding windup to RHAMT

### CODE REVIEW

**Comment by jsight** [comment]
Works for me! :)

**Comment by klinki** [comment]
It was not done yet :D (I couldn't add tag for some reason)... 
Nevermind, if it works, then it is fine :)

**Comment by jsight** [comment]
If you find more things to do, feel free to send another PR. I couldn't find any issues so far, though. :)

**Comment by jsight** [comment]
windup-web-distribution itself needed a few updates to get it to work together.

**Comment by klinki** [comment]
Ok, if it works, then great :) I still didn't test it properly, but I guess this one doesn't miss much. Probably nothing at all :)

**Pull request merged**
